# Generated by Django 3.1 on 2020-09-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tweetlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetLike',
        ),
    ]
