# Generated by Django 3.1 on 2020-09-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tweetlike'),
        ('main', '0006_auto_20200916_0929'),
    ]

    operations = [
    ]
