# Generated by Django 3.1 on 2020-09-16 04:20

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_tweet_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='content_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_search'], name='main_tweet_content_74d1d0_gin'),
        ),
    ]
